# Generated by Django 4.2.11 on 2026-04-18 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('modality', models.CharField(choices=[('XRAY', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('ULTRASOUND', 'Ultrasound')], max_length=50)),
                ('difficulty', models.CharField(choices=[('BASIC', 'Cơ bản'), ('INTERMEDIATE', 'Trung bình'), ('ADVANCED', 'Nâng cao')], default='INTERMEDIATE', max_length=20)),
                ('clinical_history', models.TextField(help_text='Lịch sử lâm sàng 2-3 dòng')),
                ('pipeline_rubric', models.JSONField(default=dict)),
                ('answer_key', models.JSONField(default=dict)),
                ('image_urls', models.JSONField(default=list, help_text='List URLs của ảnh y tế')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=0, help_text='0=OBSERVE, 1=DESCRIBE, ..., 5=CONCLUSION')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Đang làm'), ('COMPLETED', 'Hoàn thành'), ('ABANDONED', 'Bỏ cuộc')], default='IN_PROGRESS', max_length=20)),
                ('step_history', models.JSONField(default=list, help_text='[{step: 0, attempts: 1, score: 0.85}, ...]')),
                ('cv_findings', models.JSONField(default=dict, help_text='{regions: [], anomalies: [], ...}')),
                ('total_score', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='src.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'case', 'started_at')},
            },
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cases_completed', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('accuracy_by_step', models.JSONField(default=dict, help_text='{step_index: accuracy}')),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_performance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StepAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField(help_text='0-5 tương ứng với các bước')),
                ('step_name', models.CharField(editable=False, max_length=50)),
                ('student_answer', models.TextField()),
                ('score', models.FloatField(help_text='0.0 - 1.0')),
                ('errors', models.JSONField(default=list, help_text="['error1', 'error2', ...]")),
                ('feedback', models.JSONField(default=dict, help_text="{type: 'error'|'hint', content: '...'}")),
                ('latency_ms', models.IntegerField(default=0, help_text='Response time từ AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_attempts', to='src.session')),
            ],
            options={
                'ordering': ['step_index'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, to='src.casetag'),
        ),
    ]
