MEDGEMMA_GRADIO_SPACE_ID = "ttnguyen6716/MedGemma-1.5-4B"

OPENAI_IMAGE_VALIDATION_MODEL = "gpt-4o"
OPENAI_IMAGE_ANALYSIS_MODEL = "gpt-5.4-mini"
OPENAI_STEP_COMPLETION_MODEL = "gpt-4o"
OPENAI_EVALUATION_MODEL = "gpt-4o"
OPENAI_HINT_MODEL = "gpt-4o"
